denali-js/core

package.json

Couldn't use the framework without it.

Add missing 'blackburn' dependency

---

lib/cli/commands/server.js
lib/cli/commands/test.js

Solves part of #71
Might be worthwhile to print the issue url instead of the recommendation..

Fix log for vulnerable packages

---

lib/cli/commands/root.js
lib/cli/lib/command.js

Fix `--help` argument

---

config.js

Update repo and baseurl

---

guides/overview/introduction.md

Happy to recombine these into one PR if desired when I have desktop access ...

More grammatical tweaks

---

guides/data/orm-adapters.md

Three uses of your in one sentence seems a bit much ;-)

Too many uses of your

---

lib/cli/blueprints/app/files/__name__/config/middleware.js

Per guides and trial/error, `this` shouldn't be used here ;-)

[blueprint] fixed router naming

---

lib/data/model.js

Adds a memoized iterator if you need to loop over the attribute definitions for a given model.

feat(data): Add Model#eachAttribute

---

.babelrc

chore(tests): Fix babel transpile for coverage

---

lib/cli/lib/project.js
lib/utils/discover-addons.js

fix(cli): fix ability to load up addons again after changes in #123

---

bin/denali
bin/run.js

feat(cli): Check node version and error if < 6

---

cli/project.js
test/acceptance/commands/routes-test.js

This should fix the routes command, see #155

Fix create application

---

lib/index.js
lib/runtime/router.js
lib/test/mock-request.js
test/unit/router-test.js

This is basically #147 plus some additional fixes and a test.

Run middleware before routing

---

lib/runtime/router.js
test/unit/router-test.js

Supercedes #161.
Merge is blocked by #189.

Fix serializer = false support in actions

---

lib/data/model.js
test/unit/model-test.js

Fix attributes cache

---

commands/index.js

fix(cli): remove undefined index.js line from help menu

---

commands/server.js

fix(cli): stop leaking event emitters for server command

---

commands/server.js

fix(cli): Make sure cli ENVs are not overwritten by defaults

---

guides/application/routing.md

Just found this as I was perusing the documentation - I may find more documentation things so might not be a bad idea to hold off on merging for a bit 😄

fix(docs): this => router

---

guides/overview/quickstart.md

Also updated the list of files that gets generated with the new command. Fixed syntax highlighting & output on few blocks.

Updated QuickStart with required global packages

---

denali-build.js

no issue
- fixes build when denali is linked to another project and has
isDevelopingAddon set to true

fix(build): use dir rather than process.cwd()

---

lib/runtime/request.ts
test/unit/runtime/request-test.ts

- some middleware needs to access the raw socket connection

fix(request): pass through socket connection from incoming message

---

package.json

fix: Update typedoc, fixing the docs build

---

blueprints/app/files/__name__/config/environment.js

fix(blueprints): remove ormAdapter option from app blueprint

---

blueprints/app/files/__name__/app/orm-adapters/application.js

fix(blueprints): Define a default application orm-adapter

---

lib/render/json-api.ts
lib/runtime/application.ts
test/unit/render/json-api-test.ts

- Remove console.log in resolver
- Ensure application instance is registered as a singleton

Various cleanup

---

config/initializers/define-orm-models.ts
lib/data/orm-adapter.ts

This is a regression introduced in the container-injections branch. Will try and figure out some way to test this.

Model fixes

---

lib/metal/container.ts

- views need to be instantiated and they're singletons

fix(view): add view container options

---

CONTRIBUTING.md

@acburdine any other suggestions?
I plan to add more later, about debugging and submitting PRs and issues.

docs: Add a contributing.md

---

commands/publish.ts
lib/typings.d.ts
package.json

Use read-pkg to read in package.json files

---

lib/render/flat.ts
lib/render/json-api.ts
lib/render/raw.ts
lib/render/serializer.ts
lib/utils/result.ts
test/unit/render/flat-test.ts
test/unit/render/json-api-test.ts

Allow Serializer#attributes and #relationships to be a function, with access to action instance

---

lib/metal/resolver.ts
lib/runtime/application.ts
test/unit/metal/resolver-test.ts

Pass container to config to allow per-environment container overrides

---

lib/runtime/action.ts

Changing ResponderParams to be more loosely typed

---

lib/data/database.ts
lib/data/model.ts

Added better debug logging in database service and model class

Add better debug logging

---

lib/index.ts

Export DenaliObject

---

guides/testing/acceptance.md

fix(guides): appAcceptanceTest usage

---

blueprints/acceptance-test/files/test/acceptance/__name__-test.js
blueprints/resource/files/test/acceptance/__plural.name__-test.js

`appAcceptanceTest` had changed, but wasn't updated anywhere

fix(blueprints): acceptance test setup

---

CONTRIBUTING.md
commands/server.ts

This adresses #429.
Maybe this is a breaking change because its actually changing the cli API? I'm not sure about this.

modify `--debug` to be without brk and add `--debug-brk`.

---

docs/quickstart.md

Reopens #439 with the correct account.

fix: strign → string
