denali-js/core

lib/cli/blueprints/app/files/app/application.js
lib/cli/blueprints/app/files/package.json
lib/cli/server.js
lib/runtime/application.js
lib/runtime/engine.js

There were references to the port in the cli server command, but it
was never used anywhere, since 3000 was hard coded.
This now uses process.env.PORT or -p options or 3000.
Also fixed the app blueprint's npm scripts.

Add the missing -p, --port option to `denali server`

---

index.html

Noticed this while browsing the docs -> url should be relative and point to the right guide page

Fix docs link on index page

---

lib/cli/blueprints/app/index.js
package.json

I picked an arbitrary value, normally it's `200 * 1024`.
Also fixes the `npm run build` command on a new system, since the `trash` bin was missing due to missing dep.

Increase max buffer in `new`

---

src/pages/index.html

All of the links to the guides were broken

Fix guide links on homepage

---

lib/utils/topsort.js

With the update to `dag-map@2.0.0`, `addEdge` was removed and simplified down to `add`.  Makes it hard to load up add ons 😀 
More details here: https://github.com/krisselden/dag-map/pull/10

[WIP] Fixing addon loading to use new public api for dag-map

---

lib/cli/blueprints/resource/index.js

A typo in the description which showed up when using `denali g`.

[cli] Fix typo in resource blueprint description

---

lib/cli/commands/index.js
lib/cli/commands/routes.js
lib/runtime/addon.js
lib/utils/topsort.js
package.json

`denali routes` will traverse all addons and your app and print the
endpoint, method and the action.
Fixes #103 
cc @acorncom

feat(cli): New `routes` commant printing all routes

---

lib/cli/blueprints/addon/files/__name__/config/routes.js
lib/cli/blueprints/app/files/__name__/config/routes.js

Both were still referencing `this` as the way to add a route. Was more of an issue for an addon since there wasn't already a default route created.

fix(blueprints): config/routes.js comment for app and addon:

---

lib/data/serializers/json-api.js

While the spec doesn't require this, pluralizing type strings is the
recommended approach, so will stick with that.

fix(data): pluralize types in json-api serializer

---

lib/data/orm-adapters/memory.js

This is useful primarily for testing, to be able to clear the in-memory
data cache after each test.

feat(data): expose memory orm-adapter cache

---

lib/data/model.js
lib/data/orm-adapters/memory.js

The ORM adapter needs access to the user-defined model to support any additional custom options, i.e. Model.tableName

feat(data): pass model to orm adapter

---

guides/overview/app-structure.md

fix(guides): Escape *.js so it's not MD

---

lib/cli/blueprints/app/files/__name__/app/models/application.js

See https://github.com/denali-js/denali-node-orm2/pull/1#discussion_r82480573
for further discussion
Revert "remove obsolete `abstract` property from application model blueprint"
This reverts commit 59ec7e0adc237ec7b7b26eb00a0a9e98ab3e8573.

revert: data(abstract): re-add abstract property to Denali model API

---

lib/cli/blueprints/app/index.js
package.json
test/acceptance/cli/new-test.js

If yarn exists, `denali new` will use it to install dependencies rather than npm.

feat(cli): add yarn support to denali new command

---

lib/cli/blueprints/app/files/__name__/package.json

Would error if `yarn` was present during tests.

fix(blueprint): Remove duplicate eslint dep in app blueprint

---

scripts/test.sh

I got tripped up by the need to add `--` before the args I wanted to pass to Mocha, thought documenting this would save someone else some future grief ...

docs(tests): add a note about how to run --filter

---

lib/runtime/logger.js

Also makes use of the unused `logLevel` property while
also making `logger.log(msg)` a thing since it seems very natural.
Fixes #167

fix(docs): finish documenting `Logger` class

---

lib/data/serializer.js
lib/data/serializers/flat.js
lib/data/serializers/json-api.js
lib/runtime/action.js

By passing the entire response object, and not just the body, to the serializer, it allows for additional scope of customization from the serializer. For example:
* The serializer now has access to the Response's `options` hash, so actions no longer need to resort to message passing to the serializer via injecting metadata into the response body just to have the serializer strip it out.
* The serializer can add headers, like an appropriate Content-Type header or Link header for pagination.
Note that this change means the `Serializer.serialize` method is now expect to work by mutating the passed in Response object, rather than returning a response body.

feat(data): Pass entire response object to serializer

---

lib/data/serializers/flat.js
lib/data/serializers/json-api.js
lib/runtime/response.js

This PR is based off #175, so it shouldn't be merged until that one is.
This leverages the new "pass the entire response to the serializer" to change the out-of-the-box serializers to set an appropriate Content-Type header on the response.

Set content type via serializer

---

cli/lint-tree.js

Print the file and line:column in a grouped layout.
Before:
After:

fix(cli): Give linting logs a bit more context

---

test/unit/actions-test.js

Make sure the action falls back to the application
serializer if none of the types are met.

fix(test): Add action application serializer test

---

blueprints/addon/files/__name__/denali-build.js
blueprints/app/files/__name__/denali-build.js

no issue
- because it is required before any transpilation actually occurs, the `denali-build.js` file must be in vanilla-js syntax.

fix(cli): convert denali-build.js to vanilla syntax in blueprints

---

lib/runtime/container.ts

closes #242
I don't know if there are any edge cases that this will affect, but based on my knowledge of prototypal inheritance this _should_ essentially be the same behavior?
If so, then this may be able to be improved further by removing the containerizeClass function entirely.
/cc @davewasmer

fix(runtime): don't break class hasOwnProperty functionality in container

---

config/initializers/define-orm-models.ts
lib/runtime/container.ts
test/unit/container-test.ts

This PR does two things:
- adds back the availableForType method that is needed in the model class and was lost after the TS switch
- Passes the actual ModelClass in the define-orm-models initializer, instead of the base class
TODO:

Misc. ORM/Model fixes

---

lib/data/serializers/json-api.ts
lib/runtime/router.ts
test/unit/router-test.ts

This PR re-adds the router.urlFor method dropped in the TS refactor, as well as tests to prove that it works.
/cc @davewasmer I was getting typescript compile errors locally - tried fixing them several ways and couldn't figure out how - pushing this to see a) if tests work and b) get comments on how to fix the typescript warnings.

fix(router) add missing urlFor method to router

---

lib/runtime/request.ts
lib/runtime/router.ts

closes #291
- implement more of the Express Request api
- pass Request object to middleware stack rather than IncomingMessage so
that normal express middleware will function more or less the same

feat(middleware): extend Request class to match express api

---

lib/runtime/application.ts

Fixes #263 .
Adds a protected `drainers` array to Application. This will allow us to add future draining blockers, i.e. for a websockets server. I don't see a strong use case for making this userland accessible - Denali will control the major network servers (http, https, http2, websockets). If users want something else, that seems like a likely candidate for an addon, which gets it's own chance to shutdown.

Drain server connections on app shutdown

---

denali-build.js

no issue
- the typescript tree needs to run in the correct cwd to ensure that denali is built correctly

fix(build): ensure denali works correctly as a child addon

---

lib/data/descriptors.ts

no issue
- this means that model definition hooks don't have to check everywhere if an attribute or relationship's options are set before checking for individual option properties

fix(descriptors): descriptor options should default to an empty object

---

lib/data/model.ts

no issue
- startCase will split the words by spaces if they're camelcase (e.g. `fooBar` => `Foo Bar`), upperFirst won't do that.

fix(model): use upperFirst instead for dynamic model methods

---

lib/metal/container.ts
lib/metal/object.ts
lib/runtime/application.ts
test/unit/metal/container-test.ts

See #351 
Adds teardown hook to Denali Object class, which is invoked by `container.teardown()` (which itself is invoked during `application.shutdown()`).
Note that teardown() only works for container-managed singletons. Regular instances won't be invoked, nor will non-container managed singletons.
cc @seawatts

Add teardown hooks

---

lib/render/flat.ts
lib/render/json-api.ts
lib/render/serializer.ts
lib/runtime/action.ts
test/unit/render/json-api-test.ts

Fixes #347
Allows:
```
this.render(post, { attributes: [ 'title' ] });
```
Which will override the serializer's class-defined attributes whitelist.

Render attributes relationships options

---

lib/runtime/router.ts

This fixes an issue where if you have a namespaced router typescript tries to make you require the options param.

Make options optional on resource route

---

app/services/config.ts
lib/runtime/application.ts
lib/runtime/config.ts

The config service does three things:
1. Provides for a slightly simpler import/injection experience vs `inject('config:environment');`
2. Provides a safe way of attempting to access deep properties whose intermediate objects may not exist, without needing a ton of null checks. Also makes default config values easier via `getWithDefault`
4. Provides type safety for known config values, if the consuming TS code uses the `config.get('one', 'two')` syntax rather than dot notation

Add config service

---

app/views/error.html.ts
test/unit/render/view-test.ts

Cannot use `\\` in template
https://lodash.com/docs/4.17.4#template
https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L170

Fix issue with error template

---

lib/runtime/action.ts

It was already injected above anyway.

chore(action): remove commented out db injection

---

LICENSE
package.json

We are relicensing Denali under the Apache 2.0 license, primarily for the stronger patent protections. Note that this is still a permissive license - there are no copyleft provisions in Apache 2.0.
Because MIT and Apache 2.0 are considered compatible licenses, we could simply append the Apache license to the LICENSE.md file and be done.
However, since there's only a handful of contributors with non-trivial commits, it would be nice if we could get everyone to agree to relicensing their existing contributions and then we can just drop the MIT license entirely and avoid any potential future confusion.
So, with that in mind, **if you've been mentioned:**
If you agree to relicense your contributions to Denali under the Apache 2.0, please leave the following comment on this thread to indicate …

Relicense under Apache 2.0
